package ke.co.suncha.tembo.tenant.admin.system;


import ke.co.suncha.tembo.tenant.Tenant;
import ke.co.suncha.tembo.tenant.admin.models.BaseEntity;

/**
 * @author Maitha Manyala <maitha.manyala at gmail.com>
 *
 */
public class SystemOption extends BaseEntity {
	// ==============
	// PRIVATE FIELDS
	// ==============

	// An autogenerated id
	private long optionId;
	private String name;
	private String value;
	private String description="Not Available";
	private Tenant tenant;

	public long getOptionId() {
		return optionId;
	}

	public void setOptionId(long optionId) {
		this.optionId = optionId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Tenant getTenant() {
		return tenant;
	}

	public void setTenant(Tenant tenant) {
		this.tenant = tenant;
	}
}
