package ke.co.suncha.tembo.tenant.admin.users.auth;


import ke.co.suncha.tembo.tenant.admin.models.BaseEntity;
import ke.co.suncha.tembo.tenant.admin.users.User;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;

import java.io.Serializable;
import java.util.Calendar;

/**
 * @author Maitha Manyala <maitha.manyala at gmail.com>
 */
public class UserAuth extends BaseEntity implements Serializable {
    /**
     *
     */
    private static final long serialVersionUID = -3913517433663111596L;

    // An autogenerated id (unique for each user in the db)
    private long userAuthId;
    private String authPassword;
    private Calendar lastChanged = Calendar.getInstance();
    private DateTime lastAccess = new DateTime(DateTimeZone.UTC);
    private String authKey;
    private Boolean resetAuth = true;
    private String passwordResetToken;
    private Calendar passwordResetDate = Calendar.getInstance();
    private Boolean passwordResetTokenValidated = false;
    private User user;


    public Boolean getResetAuth() {
        return resetAuth;
    }

    public void setResetAuth(Boolean resetAuth) {
        this.resetAuth = resetAuth;
    }

    /**
     * @return the authPassword
     */
    public String getAuthPassword() {
        return authPassword;
    }

    /**
     * @param authPassword the authPassword to set
     */
    public void setAuthPassword(String authPassword) {
        this.authPassword = authPassword;
    }

    /**
     * @return the lastChanged
     */
    public Calendar getLastChanged() {
        return lastChanged;
    }

    /**
     * @param lastChanged the lastChanged to set
     */
    public void setLastChanged(Calendar lastChanged) {
        this.lastChanged = lastChanged;
    }

    public DateTime getLastAccess() {
        return lastAccess;
    }

    public void setLastAccess(DateTime lastAccess) {
        this.lastAccess = lastAccess;
    }

    /**
     * @param userAuthId the userAuthId to set
     */
    public void setUserAuthId(long userAuthId) {
        this.userAuthId = userAuthId;
    }

    /**
     * @return the userAuthId
     */
    public long getUserAuthId() {
        return userAuthId;
    }


    public String getAuthKey() {
        return authKey;
    }

    public void setAuthKey(String authKey) {
        this.authKey = authKey;
    }

    public String getPasswordResetToken() {
        return passwordResetToken;
    }

    public void setPasswordResetToken(String passwordResetToken) {
        this.passwordResetToken = passwordResetToken;
    }

    public Calendar getPasswordResetDate() {
        return passwordResetDate;
    }

    public void setPasswordResetDate(Calendar passwordResetDate) {
        this.passwordResetDate = passwordResetDate;
    }

    public Boolean getPasswordResetTokenValidated() {
        return passwordResetTokenValidated;
    }

    public void setPasswordResetTokenValidated(Boolean passwordResetTokenValidated) {
        this.passwordResetTokenValidated = passwordResetTokenValidated;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /*
             * (non-Javadoc)
             *
             * @see java.lang.Object#toString()
             */
    @Override
    public String toString() {
        return "UserAuth [userAuthId=" + userAuthId + ", authPassword=" + authPassword + ", dateAdded=" + this.getCreatedOn() + ", lastChanged=" + lastChanged + ", lastAccess=" + lastAccess + "]";
    }
}